# horizon images

## Core components
consul1:
  build: containers/consul/
  ports:
    - "8500:8500"
  environment:
    CONSUL_NODE_NAME: consul1

consul2:
  build: containers/consul/
  ports:
    - "9500:8500"
  environment:
    CONSUL_NODE_NAME: consul2
    CONSUL_SEED_NODE: consul1
  links:
    - consul1

consul3:
  build: containers/consul/
  ports:
    - "10500:8500"
  environment:
    CONSUL_NODE_NAME: consul3
    CONSUL_SEED_NODE: consul1
  links:
    - consul1

## Data Transit

zookeeper1:
  build: containers/zookeeper/
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
  volumes:
    - /opt/zookeeper/conf:/opt/zookeeper/conf
    - /tmp/zookeeper:/tmp/zookeeper

kafka1:
  build: containers/kafka/
  ports:
    - "9092:9092"
  volumes:
    - /opt/kafka:/opt/kafka
  environment:
    KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181/kafka

## Data Storage

postgres:
  build: containers/psql/
  ports:
    - "5432:5432"
  restart: always
  environment:
    POSTGRES_DB: horizon
    POSTGRES_HOSTNAME: 192.168.59.103
    POSTGRES_USER: horizon
    POSTGRES_PASSWORD: e06b4ed2b382f68
  volumes:
    - /var/lib/postgresql/data/:/var/lib/postgresql/data/
    - /var/log/postgresql/:/var/log/postgresql/

## Metrics

influxdb1:
  image: tutum/influxdb
  ports:
   - "8083:8083"
   - "8086:8086"

grafana:
  image: grafana/grafana
  ports:
   - "3000:3000"
  links:
   - influxdb1
