# horizon docker-compose

xtreemfsclient:
  image: xtreemfs/xtreemfs-client
  command: /bin/bash
  privileged: true

xtreemfsdir:
  image: xtreemfs/xtreemfs-dir
  net: host
  volumes:
    - "configs/:/xtreemfs_data"
  ports:
    - "30638:30638"
    - "32638:32638"

xtreemfsmrc:
  image: xtreemfs/xtreemfs-mrc
  net: host
  volumes:
    - "configs/:/xtreemfs_data"
  ports:
    - "30636:30636"
    - "32636:32636"

# horizon1
xtreemfsosd1:
  image: xtreemfs/xtreemfs-osd
  net: host
  volumes:
    - "configs/osd1/:/xtreemfs_data"
  ports:
    - "30640:30640"
    - "32640:32640"

xtreemfsosd2:
  image: xtreemfs/xtreemfs-osd
  net: host
  volumes:
    - "configs/osd2/:/xtreemfs_data"
  ports:
    - "30642:30642"
    - "32642:32642"

# horizon2 (8gig)
xtreemfsosd2:
  image: xtreemfs/xtreemfs-osd
  net: host
  volumes:
    - "configs/osd3/:/xtreemfs_data"
  ports:
    - "30640:30640"
    - "32640:32640"